#PetReminder Storage Configuration
#Thu Mar 26 14:30:50 TRT 2026
storage.backend=SQLITE
binary.dir=data/binary
mysql.url=jdbc\:mysql\://localhost\:3306/petreminder_db?useSSL\=false&serverTimezone\=UTC
mysql.password=petreminder_pass
mysql.username=petreminder_user
sqlite.path=data/petreminder.db
