#PetReminder Storage Configuration
<<<<<<< Updated upstream
#Sat Mar 14 16:09:10 EET 2026
storage.backend=BINARY
=======
#Wed Mar 18 18:53:11 TRT 2026
storage.backend=SQLITE
>>>>>>> Stashed changes
binary.dir=data/binary
mysql.url=jdbc\:mysql\://localhost\:3306/petreminder_db?useSSL\=false&serverTimezone\=UTC
mysql.password=petreminder_pass
mysql.username=petreminder_user
sqlite.path=data/petreminder.db
