#PetReminder Storage Configuration
#Tue Mar 24 18:17:37 EET 2026
storage.backend=BINARY
binary.dir=data/binary
mysql.url=jdbc\:mysql\://localhost\:3306/petreminder_db?useSSL\=false&serverTimezone\=UTC
mysql.password=petreminder_pass
mysql.username=petreminder_user
sqlite.path=data/petreminder.db
