#PetReminder Storage Configuration
<<<<<<< Updated upstream
#Thu Mar 26 11:53:54 TRT 2026
storage.backend=SQLITE
=======
#Wed Mar 25 16:41:08 TRT 2026
storage.backend=BINARY
>>>>>>> Stashed changes
binary.dir=data/binary
mysql.url=jdbc\:mysql\://localhost\:3306/petreminder_db?useSSL\=false&serverTimezone\=UTC
mysql.password=petreminder_pass
mysql.username=petreminder_user
sqlite.path=data/petreminder.db
